### ISSUE TITLE
distance函数的使用疑问

### ISSUE THREAD

**Issue by zheguzai100** [qinwf/jiebaR#13]
#### [distest.txt的内容]<h4>
*abd1: 这是第一行吧算是
mmmm2: 我把这个设置成第二行可以吗
sho3: what r you talking about ?!
sdjh4: may i have a word with u ?
whkshdf5: i wanna talk to u.*

----------------------------------------------------------
```r 
data=read.table('I:/rwork/cnseg/distest.txt',header=FALSE,encoding='UTF-8',sep=':')
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  line 2 did not have 3 elements

想实现的效果
1.通过read.table读取txt文件为data
2.通过 ‘:’(冒号) 将数据拆分为两列，并通过row.names(data)=data[,1];data=data[,2]
3.通过distance函数计算文本文件内 行与行之间的距离
(经测试distance可以计算两个语句之间or两个文本文件之间的距离，
 但是文本文件内的任意两句之间的距离不知该如何操作)
```

**Comment by qinwf** [comment]
这是 R 的基本的数据操作，推荐 [几本书](https://github.com/qinwf/awesome-R#books)。The Art of R Programming 可以入门，[Adv R](http://adv-r.had.co.nz/) 适合进阶。
