### ISSUE TITLE
关于distance的疑问

### ISSUE THREAD

**Issue by zheguzai100** [qinwf/jiebaR#14]
根据 [Simhash 与海明距离] (http://qinwenfeng.com/jiebaR/quick/sim.html) 的介绍，是先分词 继而提取关键字 再计算simhash值和海明距离。 

疑问： 分词之后在提取关键字的时候是不是依靠tf_idf值？ 如果是，那么 tf_idf= tf比率 * idf值(是否直接从jiebaRD-dict-idf.utf8中获取的？) 如果在idf.utf8文件中不存在这个关键词是不是意味着他就没有tf_idf值也就不会出现在关键词中？

**Comment by qinwf** [comment]
如果查idf表中，不存在则取均值。
