### ISSUE TITLE
在其他的R套件中的C/C++函數中呼叫jiebaR做分詞

### ISSUE THREAD

**Issue by wush978** [qinwf/jiebaR#15]
Hi, 

我是 [FeatureHashing](https://github.com/wush978/FeatureHashing)的作者。目前FeatureHashing的套件中具備有直接對英文語句做斷詞（split）後直接利用hashing trick產生 sparse matrix 給更進一步的機器學習套件使用。（e.g.： <https://github.com/wush978/FeatureHashing/blob/master/vignettes/SentimentAnalysis.Rmd>）

我很有興趣在FeatureHashing中也提供jiebaR的斷詞功能。由於核心功能都是用Rcpp開發的，所以想要問問你有沒有興趣提供接口（大概類似 https://github.com/eddelbuettel/digest/pull/10 ），讓FeatureHashing或第三方套件可以在C/C++中直接呼叫jiebaR的分詞功能呢？

Wush

**Comment by qinwf** [comment]
CppJieba 是 header only的，jiebaR 使用的时候，第一步是先在 R 用 worker() 函数生成 一个指定分词方法 C++ 对象，这些对象在定义在 jiebaR/inst/include/segtype.hpp 里。这个对象包括了读取的词库和分词模型，可以反复调用， 是一个类似智能指针的东西，

```c++
 XPtr<mpseg> mp_ptr(const CharacterVector& dict, const CharacterVector& user){
  return( XPtr<mpseg>(new mpseg(dict, user))) ;
}
```

XPtr 类是 Rcpp 对 R 的 C 接口的智能指针的封装。这个指针由 R 的 GC 负责回收。

分词阶段，会调用这个智能指针指向类的相应方法比如 cut 进行分词。

C++ 接口对应函数操作的是 UTF-8 格式的一段文本，为了保证平台间的一致性，其他的预处理工作比如编码转换、正则表达式处理的内容在 R 的对应函数里完成。

比如在 Windows 平台上，直接输出 UTF-8 的文本有时候会乱码，还有这个平台上经常出现各种不同类型的编码，所以分词前可以用 filecoding 函数判断文本的编码（函数是用c++实现的，在 jiebaR/src/detect.cpp），如果不是 UTF-8 编码，使用 R 里面的 iconv 函数进行对应的转换，最后把相应文本输入到 C++ 的对应接口里进行分词操作。

如果要直接使用 c++ 接口的，你可能还需要处理不同平台的文本编码和文本预处理问题。

**Comment by wush978** [comment]
我是可以直接使用CppJieba，但是正如你提到的一些問題，我更想直接呼叫jiebaR的函數，如 `jiebaR_mix_cut`。

如果jiebaR套件要讓其他R套件在C呼叫`jiebaR_mix_cut`，需要做：

- 在`src/init.c`中註冊如`jiebaR_mix_cut`函數給R
- 在`inst/include`之中提供`jiebaR_mix_cut`的宣告給第三方套件（如FeatureHashing）來include

我之前有幫`digest`做過這部份的工作，細節可以參考 <https://github.com/eddelbuettel/digest/pull/10/files> 。如果你有興趣的話，我可以發個PR給你，這樣其他R套件只要在`DESCRIPTION`中放入`LinkingTo: jiebaR`和一些必要步驟，就可以直接調用你實作的函數，如`jiebaR_mix_cut`

**Comment by qinwf** [comment]
嗯嗯，待会我写一下。

**Comment by qinwf** [comment]
init_c 分支可以用了，我再写一下测试代码。现在 API 没有检查传入的函数指针是不是正确的，需要调用者来确保，不要把 mp_ptr 传到 key_ptr。 

Windows 平台 API 分词结果的文本直接传入 R 调用 print() 会乱码，jiebaR 包的解决方法是

```r
if (.Platform$OS.type == "windows") {
        Encoding(tmp_result)<-"UTF-8"
}
```

调用 jiebaR::HMMPATH 寻找词典路径的对应值是在运行时加载命名空间时确定的。

**Comment by wush978** [comment]
謝謝，我會試試看，有結果再跟你討論。

**Comment by qinwf** [comment]
我在考虑在把停止词的功能加到分词过程里，这样 C 接口有可能会变化，就是
mp_ptr， mix_ptr， query_ptr， hmm_ptr 这个四个初始化 worker 的函数会增加一个参数 Nullable<CharacterVector> stop。现在还不确定是否要添加。变化会在 cpp_stopwords 分支。

**Comment by qinwf** [comment]
`Nullable<CharacterVector> stop` 需要 Rcpp 0.12.1 版本。

**Comment by wush978** [comment]
我知道了，謝謝通知

**Comment by wush978** [comment]
請問如果要測試串C的API的話，有建議用哪一個branch嗎？

**Comment by qinwf** [comment]
可以用 master 了，我已经把最新的变更合并了。

**Comment by wush-bridgewell** [comment]
不好意思，再請教一個問題。

我目前是先在R建立一個cutter:

```r
cutter <- worker(type = "mix")
```

然後想要在C呼叫:

```cpp
jiebaR_mix_cut(string, Rcutter)
```

但是看一下你的原始碼，第二個參數`Rcutter`這邊是吃一個 `XPtr`

爬了一下cutter的結構，是不是要用：

```r
cutter$worker
```

的這個pointer傳給`jiebaR_mix_cut`這個c函數呢？

又請問，能不能讓jiebaR提供一個API，自動取出R cutter呢？

謝謝

**Comment by qinwf** [comment]
XPtr<mixseg> mix_ptr(...){
  return( XPtr<mixseg>(new mixseg(dict, model, user, stop))) ;
}

就是直接传这个指针，在 R 里面的 cutter 是我用 list 把这个指针包了一下。API 函数的返回值，就是可以直接用的那个。

```r
  cutter = jiebaRapi:::mix_ptr(jiebaR::DICTPATH,jiebaR::HMMPATH,jiebaR::USERPATH,jiebaR::STOPPATH)
  expect_equal(jiebaRapi:::mix_cut("this is test",cutter),c("this", " ", "is", " ", "test"))
```

这里有一些测试 API 接口的代码：
https://github.com/qinwf/jiebaR/blob/master/tests/testthat/CPP_API/tests/testthat/test-cpp.R 
https://github.com/qinwf/jiebaR/blob/master/tests/testthat/CPP_API/src/test_api.cpp
你可以参考一下。

**Comment by qinwf** [comment]
我的测试代码里面没有中文，应为 CRAN 不给放。如果输入文本有中文，建议用

jiebaR:::mix_cut(enc2utf8(c("中文","sdssss")),cutter)

在 Windows 平台加上 enc2utf8 ，因为可能会乱码。

**Comment by wush978** [comment]
謝謝，我已經完成相關功能的串接了。

預計會發布於v0.10版。

**Comment by qinwf** [comment]
嗯嗯，这个版本还没有发布到 CRAN，我再测试一些其他功能，国庆节左右推到 CRAN 吧。

**Comment by wush978** [comment]
謝謝，麻煩你了。
