### ISSUE TITLE
切分`..`出现`Error: Cannot open file`错误

### ISSUE THREAD

**Issue by scjiaer** [qinwf/jiebaR#17]
使用jiebaR进行分词的时候，出现Error: Cannot open file
```r
library(jiebaR)
seg=worker()
segment('..',seg)
```
缘起于自己在处理诸如`2014.01.23`字符串的时候，当通过tm_map删掉数字后，发现仅剩`..`，而这个字符直接导致上述报错，应该是来自[detect.cpp](https://github.com/qinwf/jiebaR/blob/master/src/detect.cpp)，猜测可能是把它当成了路径？！

**Comment by qinwf** [comment]
用NOFILE 

http://qinwenfeng.com/jiebaR/basic/new.html

四、增加： write = "NOFILE" 选项，不检查文件路径。

cutter = worker(write = "NOFILE",symbol = TRUE)
cutter["./test.txt"] # 目录下有test.txt 文件
[1] "."    "/"    "test" "."

**Comment by scjiaer** [comment]
赞！
