### ISSUE TITLE
在windows下使用的時候返回信息中的亂碼

### ISSUE THREAD

**Issue by ijasmine** [qinwf/jiebaR#19]
我在windows 7下使用jiebaR對一個文本文件（UTF-8編碼）進行分詞，由於incomplete final line的問題，會返回一個錯誤信息，這個信息裡面的文件名編碼是用的GBK編碼吧。
例如我使用如下的命令
segmentParSet1 <= "寂寞像一只蚊子.txt"
返回是 
In readLines(input.r, n = lines, encoding = encoding) : incomplete final line found on '瀵傚癁鍍忎竴鍙殜瀛?txt'
雖然在文件管理器顯示產生的新文件的文件名是
寂寞像一只蚊子.segment.2015-12-09_18_34_49，
但是為什麼在R console窗口裡面的時候，是那一串亂碼，是將原來的文件名以GBK方式輸出的結果。雖然對結果沒有什麼影響，但是這個可以修改嗎？
謝謝

**Comment by qinwf** [comment]
Windows 编码问题比较复杂。比如， R 交互的命令行界面输入文本显示正常，但是输出文本有可能乱码，这是因为 Windows 默认的命令行的编码对 UTF-8 格式支持不好，但是实际文本是可以正确识别的。有的时候你输入文本是显示是好的，但是显示在命令行的输出结果里却是乱码。使用 enc2utf8("待处理文本") 或者 Encoding(c("待处理文本")) = "UTF-8" 可以解决输入文本正常，但是命令行显示乱码的问题。

这个问题只在 Windows 上存在，其他平台不会有。这个也不能算是 R 的问题，主要是 Windows 命令行对 UTF-8 文本的显示支持问题。

In readLines(input.r, n = lines, encoding = encoding) : incomplete final line found on 这个警告信息是因为在文件读取过程中，被读取的文件最后一行没有空行，所以会有，一般不会对读取文件结果造成影响。见 http://qinwenfeng.com/jiebaR/faq/warnings.html

jiebaR 在处理分词文本的时候，如果用户没有指定输入的文本编码格式，会使用 filecoding 函数探测文本编码，并对非 UTF-8 文本使用 iconv 函数进行转换。如果指定了输入的文本编码，则不探测文本编码，如果设置的输入编码不是 UTF-8 ，则对输入文本进行编码转换。

文本编码检测并不是 100% 准确的，有一定的置信区间，因为不同编码文本格式的信息之间有一定的重叠。除了 filecoding 函数，还有 https://github.com/qinwf/checkenc 这个包可以进行编码的检测。

现在如果你的待分词文本是UTF-8格式的，那么分词的结果应该是没有问题的。只是 R 这个警告信息在打印到 Windows 命令行输出的时候把 文件名 输出成乱码了。

**Comment by ijasmine** [comment]
謝謝！我試了一下，在ubuntu下使用確實沒有亂碼。謝謝
