### ISSUE TITLE
词性标注不正确

### ISSUE THREAD

**Issue by fanxiong** [qinwf/jiebaR#21]
> tagger <= "我刚刚在桌子旁边不小心摔坏了一只装水的杯子"
     r      d         p      n        f           d      n        v          ul      m      x 
  "我" "刚刚"   "在" "桌子" "旁边"   "不" "小心" "摔坏"   "了" "一只" "装水" 
    uj      n 
  "的" "杯子" 
上面例子中的"装水"词性不明确,  "摔坏",   "了" 是不是分成"摔"+"坏了" 更恰当？

**Comment by qinwf** [comment]
现在词性标注是通过查字典的方式确认的，一个词对应一个词性，可能会不准确，如果需要更准确的词性标注，可以使用其他的工具 。

默认词典里面有 “摔坏” 这个词，可以删除 “摔坏” 这个词后，增加 “坏了” 这个词，并设置足够大的词频让能够被分出来。对于“摔坏了”， “坏了”这个词在默认加载的词典里词频设置在 48 左右可以被分出来。

不同人以及不同分析场景对“词”的概念界定可能会不太一样，所有这个可以根据实际需要变动。

**Comment by fanxiong** [comment]
感谢你的回答。对于上述原因我能够理解，同时我也想问问：如果我在不删除"摔坏“一词的情况下，增加"坏了"，并设置词性和词频，是否可以被识别出来呢？

2016-01-16 22:07 GMT+08:00 Qin Wenfeng <notifications@github.com>:

> 现在词性标注是通过查字典的方式确认的，一个词对应一个词性，可能会不准确，如果需要更准确的词性标注，可以使用其他的工具 。
>
> 默认词典里面有 “摔坏” 这个词，可以删除 “摔坏” 这个词后，增加 “坏了” 这个词，并设置足够大的词频让能够被分出来。对于“摔坏了”，
> “坏了”这个词在默认加载的词典里词频设置在 48 左右可以被分出来。
>
> 不同人以及不同分析场景对“词”的概念界定可能会不太一样，所有这个可以根据实际需要变动。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qinwf/jiebaR/issues/21#issuecomment-172209004>.
>



-- 

========================================
addr: *北京捷能瑞控科技有限公司*
 tel: *010-62417616*
mail: *qian.xiong2005@gmail.com <qian.xiong2005@gmail.com>*

**Comment by qinwf** [comment]
可以，但是可能需要稍微大一些的词频。
