### ISSUE TITLE
Problem with dev version of devtools

### ISSUE THREAD

**Issue by hadley** [qinwf/jiebaR#22]
```
checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  12: test("./CPP_API")
  13: load_all(pkg, quiet = TRUE) at /Users/hadley/Documents/devtools/devtools/R/test.r:50
  14: check_suggested("roxygen2") at /Users/hadley/Documents/devtools/devtools/R/load.r:88
  15: check_dep_version(pkg, version, compare) at /Users/hadley/Documents/devtools/devtools/R/utils.r:63
  16: stop("Dependency package ", dep_name, " not available.") at /Users/hadley/Documents/devtools/devtools/R/package-deps.r:56
  
  testthat results ================================================================
  OK: 14 SKIPPED: 0 FAILED: 2
  1. Error: C_API 
  2. Error: CPP_API 
  
  Error: testthat unit tests failed
  Execution halted
```

Could you please look into this as soon as possible? I really want to release devtools to CRAN in the next couple of days so that I can use the latest version in class next week.

From the error, I'm guess it's something to do with roxygen2, which devtools now only suggests, instead of requiring.

**Comment by qinwf** [comment]
Thanks for the report, I will look into this today.

**Comment by qinwf** [comment]
@hadley 

https://github.com/qinwf/devtools/commit/5df24327485496551d4f4218df7fa8d58523acc3

This change will fix the problem, or I can add roxygen2 to jiebaR Suggests will also fix this.

**Comment by qinwf** [comment]
jiebaR use `devtools::test()` in test srcipts in this file https://github.com/qinwf/jiebaR/blob/master/tests/testthat/test-api.R

**Comment by qinwf** [comment]
Shall we add roxygen2 to jiebaR Suggests to fix this problem, or you will modify devtools. 

jiebaR did not directly call roxygen2 in the test.

**Comment by hadley** [comment]
Hmmm, it's strange to call `test()` inside a test suite - it needs roxygen2 because `load_all()` calls `roxygen2::update_collate()` in order to load the files in the correct order.

What motivated your current approach of putting tests in separate package? A better approach might be to add additional files in `tests/` that install the package then run `test_check()`

**Comment by qinwf** [comment]
I see this commit, https://github.com/hadley/devtools/commit/84a8e3f0710b14e4631f3bce195a4b0db035a563

I need to test some cpp api that will be used by other packages. I think adding roxygen2 to jiebaR `Suggests` would be better choice.

I will try to get it to CRAN, but I do not know whether the Clang 3.8 RC issue #24 will block the release. http://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/jiebaR/tests/

I can not reproduce the Clang 3.8 RC issue for now.
