### ISSUE TITLE
添加新词无效

### ISSUE THREAD

**Issue by jiang-hang** [qinwf/jiebaR#30]
我使用的是jiebaR  0.8，  ubuntu15.10 ,  问题如下：

> library(jiebaR)
载入需要的程辑包：jiebaRD
> seg=worker()
> new_user_word(seg,"北京大学","n")
[1] TRUE
> seg["北京大学"]
[1] "北京" "大学"
> 

其中“北京大学”并没有作为一个单词被分出来，而是变成了两个词。

**Comment by BruceZhaoR** [comment]
请看issue #29 虽然刚刚关闭～


From BruceZhao's iPhone.

**Comment by jiang-hang** [comment]
谢谢， 指定user_weight就可以工作了。
