### ISSUE TITLE
请教关于distance的问题

### ISSUE THREAD

**Issue by BruceZhaoR** [qinwf/jiebaR#34]
我用[stringdist](https://github.com/markvanderloo/stringdist)包计算的hamming距离与用jiebaR计算的distance距离不一致，是不是我使用方法有问题啊？
参考链接：<https://qinwenfeng.com/jiebaR/sim.html>
测试一：
```r
library(jiebaR)
words = "hello world!"
simhasher = worker("simhash",topn=2)
distance(words, "江州市长江大桥参加了长江大桥的通车仪式",simhasher)

a <- tobin(simhasher[words]$simhash)
b <- tobin(simhasher["江州市长江大桥参加了长江大桥的通车仪式"]$simhash)
stringdist::stringdist(a,b,method = "hamming")
```

测试二：
```r
sim = worker("simhash")
vector_distance(c("今天","天气","真的","十分","不错","的","感觉"),c("真的","十分","不错","的","感觉"),sim)

res = vector_simhash(c("今天","天气","真的","十分","不错","的","感觉"),sim) 
a<-tobin(res$simhash)
res1 = vector_simhash(c("真的","十分","不错","的","感觉"),sim)
b<-tobin(res1$simhash)
stringdist::stringdist(a,b,method = "hamming")
```

**Comment by qinwf** [comment]
没有很仔细读 `stringdist` 源代码，但是初略看一下它输入数据是文本，比较的是文本的距离，也就是 simhash 数值对应文本的距离，而不是两个 simhash 数值的数据。而distance 对应的函数是用 simhash 数值计算的。

https://github.com/markvanderloo/stringdist/blob/master/pkg/src/Rstringdist.c#L54

https://github.com/qinwf/jiebaR/blob/master/inst/include/lib/Simhasher.hpp#L163-L174

**Comment by BruceZhaoR** [comment]
@qinwf 
我看过hamming距离的定义，两个变量取 XOR 然后sum就是hamming距离，简单粗暴。

simhash好像不太一样，不单纯的计算距离，而是在计算距离的基础上加工了。不知道我有没有理解正确? 参考文章：<http://yanyiwu.com/work/2014/01/30/simhash-shi-xian-xiang-jie.html>

另外，这个distance返回的是单个的值，能不能也像stringdist包一样加上stringdistmatrix函数，直接可以返回距离矩阵，方便后面的分析。估计实现起来很难啊，等你哪天有空再弄弄。

**Comment by qinwf** [comment]
simhash 先对一个句子提取出若干个关键词，然后对关键词进行 hash 操作，得到 simhash 值。distance 函数这里计算的 hamming 距离是两个 simhash 值的距离。

https://github.com/qinwf/jiebaR/blob/master/inst/include/lib/Simhasher.hpp#L163-L174

```cpp
 static uint64_t distances(uint64_t lhs, uint64_t rhs)
{
     uint64_t cnt = 0;
     lhs ^= rhs;
     while(lhs != 0)
     {
          lhs &= lhs - 1;
          cnt++;
     }
    return cnt;
}
```

`lhs ^= rhs;`  是求异或的步骤。

这里的

```cpp
while(lhs != 0)
{
   lhs &= lhs - 1;
   cnt++;
}
```

是求和的步骤。

**Comment by qinwf** [comment]
可以把 `static uint64_t distances(uint64_t lhs, uint64_t rhs)` 这个函数从 C++ 里接口到 R ，用户就可以直接用来，求距离矩阵应实现起来应该不难。

**Comment by BruceZhaoR** [comment]
那 `tobin` 这个函数是干啥用的？ 我之前以为这个就是用来计算distance的，所以我把simhash的值转为64位的01，然后用这个来求hamming距离。所以才提了这个issue。

**Comment by qinwf** [comment]
`tobin` 是把十进制表示的数值转换为二进制表示的数值。

**Comment by BruceZhaoR** [comment]
265547a0f6c22cd1ec16eb06e27dbc729187ee07

close.

**Comment by BruceZhaoR** [comment]
Bug report：  `simhash_dist`计算出来的与`distance`计算出来的hamming距离不一致。

```r
> simhasher = worker("simhash",topn = 2)
> vector_distance(c("今天","天气","真的","十分","不错","的","感觉"),c("真的","十分","不错","的","感觉"),simhasher)
$distance
[1] 34

$lhs
6.45994 6.18823 
 "天气"  "不错" 

$rhs
6.18823 5.64148 
 "不错"  "感觉" 

> vector_simhash(c("今天","天气","真的","十分","不错","的","感觉"),simhasher)
$simhash
[1] "12098690169796312660"

$keyword
6.45994 6.18823 
 "天气"  "不错" 

> vector_simhash(c("真的","十分","不错","的","感觉"),simhasher)
$simhash
[1] "13211561198063535373"

$keyword
6.18823 5.64148 
 "不错"  "感觉" 

> simhash_dist("12098690169796312660","13211561198063535373")
[1] 50

> stringdist::stringdist(tobin("12098690169796312660"),tobin("13211561198063535373"),method = "hamming")
[1] 50

```
 这个跟我之前用`stringdist`计算的结果一样了啊。 @qinwf  cc

**Comment by qinwf** [comment]
我把一些中间结果打印出来了，是新加入的 `simhash_dist` 字符串转换数字的时候有问题，我待会改一下。

```r
vector_distance(c("今天","天气","真的","十分","不错","的","感觉"),c("真的","十分","不错","的","感觉"),simhasher)
#> x = 12098690169796312660
#> y = 13211561198063535373
#> 34

> simhash_dist("12098690169796312660","13211561198063535373")
#> x = 1793672461
#> y = 18446744072001961556
#> 50
```

这里 simhash 得到的结果是 64 位的整数，超过了 R 的整数范围。`simhash_dist` 会先把这个文本转化为数字，然后再计算距离。

**Comment by qinwf** [comment]
`simhash_dist` 和 `tobin` 已经修复了，感谢 @BruceZhaoR 的反馈！

**Comment by BruceZhaoR** [comment]
@qinwf  完美解决了！
```r
> simhash_dist("12098690169796312660","13211561198063535373")
[1] 34
```

**Comment by BruceZhaoR** [comment]
已经完美解决！
