### ISSUE TITLE
无法从github下載安装jiebaR

### ISSUE THREAD

**Issue by Benknightdark** [qinwf/jiebaR#38]
Hi @qinwf ,
我利用Rstudio的devtools套件安装目前在github的jiebaR套件，可是在安装jiebaR会发生下列错误：「'stoull' was not declared in this scope」。

![image](https://cloud.githubusercontent.com/assets/5799487/17053395/5499eb78-5034-11e6-84fe-2e2b8744dade.png)

我安装的R言版本如下图所示：
![image](https://cloud.githubusercontent.com/assets/5799487/17053399/583f786a-5034-11e6-8c5f-4b9734196602.png)

计算机的gcc版本如下图所示：

![image](https://cloud.githubusercontent.com/assets/5799487/17053400/5a6d7718-5034-11e6-9723-0328a761f576.png)

**Comment by qinwf** [comment]
GitHub 上的开发版使用了 C++11 的 stoull ，请更新 Rtools 到最新版本，以及更新 R 到 3.3.0 以上即可。

**Comment by Benknightdark** [comment]
@qinwf ，感谢你的帮忙，已解决问题
