### ISSUE TITLE
package cidian, decode_scel error

### ISSUE THREAD

**Issue by zheguzai100** [qinwf/jiebaR#41]
decode_scel(scel = "D:/Sougou/SogouInput/8.0.0.8381/scd/14108.scel",
+             output = "D:/R/R-3.3.1/library/jiebaRD/dict/sougou.dict",
+             cpp = TRUE)

Error in eval(substitute(expr), envir, enclos) : not a valid .scel file?

Anything wrong in coding ?

**Comment by qinwf** [comment]
Thanks for your report, but I am sorry that I can not reproduce your error.

Can you please provide a scel file that can reproduce this error?

**Comment by zheguzai100** [comment]
it's in sougou's latest pck 8.xxx in http://pinyin.sogou.com/
and scel file is here, thanks for yr reply
链接: `http://pan.baidu.com/s/1kVNO8f1` 密码: s5w8

**Comment by qinwf** [comment]
[14108.scel_2016-10-19_13_37_56.txt](https://github.com/qinwf/jiebaR/files/538029/14108.scel_2016-10-19_13_37_56.txt)

Hi, please install_github the latest version of cidian, it should work now. The attachment is the dict that I just generated.

**Comment by Jackkong008** [comment]
安装不上，出现如下问题，如何解决
> library(devtools)
> install_github("qinwf/cidian")
Downloading GitHub repo qinwf/cidian@master
Installing cidian
"D:/Program Files/Microsoft SQL Server/130/R_SERVER/bin/x64/R"  \
  --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/Administrator/AppData/Local/Temp/2/Rtmpc7CGjB/devtools4fec35d2ccc/qinwf-cidian-3002bf4"  \
  --library="D:/Program Files/Microsoft SQL Server/130/R_SERVER/library"  \
  --install-tests 

'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
错误: Command failed (1)

**Comment by qinwf** [comment]
请问是否安装了 devtools 呢？

**Comment by qinwf** [comment]
我这几天会把这个更新后的版本发到 CRAN 上

**Comment by BruceZhaoR** [comment]
你这个情况是安装路径的问题，我碰到过。Program Files文件夹中间有空格，建议把R装在D盘的根目录下面。


From BruceZhao's iPhone.
在2017年02月19日 23:54，Jackkong008 写道:

安装不上，出现如下问题，如何解决

library(devtools)
install_github("qinwf/cidian")
Downloading GitHub repo qinwf/cidian@master
Installing cidian
"D:/Program Files/Microsoft SQL Server/130/R_SERVER/bin/x64/R"
--no-site-file --no-environ --no-save --no-restore CMD INSTALL
"C:/Users/Administrator/AppData/Local/Temp/2/Rtmpc7CGjB/devtools4fec35d2ccc/qinwf-cidian-3002bf4"
--library="D:/Program Files/Microsoft SQL Server/130/R_SERVER/library"
--install-tests

'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
错误: Command failed (1)

**Comment by Jackkong008** [comment]
谢谢楼上，我试试
