### ISSUE TITLE
在microsoft-r 3.3.1@ubuntu16.04下安装jiebaR提示找不到include目录

### ISSUE THREAD

**Issue by alexwwang** [qinwf/jiebaR#42]
无论是从CRAN的repo还是使用install_github安装，
无论是安装到用户library路径还是系统library路径，都出现同样的错误，
提示：sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory

具体报错信息如下：
`* installing *source* package ‘jiebaR’ ...`

`** libs`

`I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include -DLOGGING_LEVEL=LL_WARNING  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o`

`sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory`

`/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'RcppExports.o' failed`

`make: [RcppExports.o] Error 127 (ignored)`

`I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include -DLOGGING_LEVEL=LL_WARNING  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c detect.cpp -o detect.o`

`sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory`

`/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'detect.o' failed`

`make: [detect.o] Error 127 (ignored)`

`I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include -DLOGGING_LEVEL=LL_WARNING  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c get_idf.cpp -o get_idf.o`

`sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory`

`/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'get_idf.o' failed`

`make: [get_idf.o] Error 127 (ignored)`

`I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include -DLOGGING_LEVEL=LL_WARNING  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c get_tuple.cpp -o get_tuple.o`

`sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory`

`/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'get_tuple.o' failed`

`make: [get_tuple.o] Error 127 (ignored)`

`gcc -std=gnu99 -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include -DLOGGING_LEVEL=LL_WARNING  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATION -O2 -g  -c init.c -o init.o`

`I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include -DLOGGING_LEVEL=LL_WARNING  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c segtype-v4.cpp -o segtype-v4.o`

`sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory`

`/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'segtype-v4.o' failed`

`make: [segtype-v4.o] Error 127 (ignored)`

`I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include -DLOGGING_LEVEL=LL_WARNING  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c util.cpp -o util.o`

`sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory`

`/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'util.o' failed`

`make: [util.o] Error 127 (ignored)`

`I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include -DLOGGING_LEVEL=LL_WARNING  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include"      -c word_freq.cpp -o word_freq.o`

`sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory`

`/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'word_freq.o' failed
make: [word_freq.o] Error 127 (ignored)`

`-shared -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -o jiebaR.so RcppExports.o detect.o get_idf.o get_tuple.o init.o segtype-v4.o util.o word_freq.o -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -lR`

`sh: line 2: -shared: command not found`

`/usr/lib64/microsoft-r/3.3/lib64/R/share/make/shlib.mk:6: recipe for target 'jiebaR.so' failed`

`make: *** [jiebaR.so] Error 127`

`ERROR: compilation failed for package ‘jiebaR’`

`* removing ‘/home/da/R/x86_64-pc-linux-gnu-library/3.3/jiebaR’`

`Error: Command failed (1)`

session_Info():
Session info ------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.902)          
 language (EN)                        
 collate  zh_CN.UTF-8                 
 tz       PRC                         
 date     2016-10-26                  

Packages ----------------------------------------------------------------------------------------------------------------------
 package       * version date       source        
 colorspace      1.2-6   2015-03-11 CRAN (R 3.3.0)
 devtools      * 1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest          0.6.9   2016-01-08 CRAN (R 3.2.5)
 ggplot2         2.1.0   2016-03-01 CRAN (R 3.3.0)
 gtable          0.2.0   2016-02-26 CRAN (R 3.3.0)
 memoise         1.0.0   2016-01-29 CRAN (R 3.2.5)
 munsell         0.4.3   2016-02-13 CRAN (R 3.3.0)
 plyr            1.8.4   2016-06-08 CRAN (R 3.3.1)
 Rcpp            0.12.5  2016-05-14 CRAN (R 3.3.0)
 RevoUtils       10.0.1  2016-08-24 local         
 RevoUtilsMath * 10.0.0  2016-06-15 local         
 scales          0.4.0   2016-02-26 CRAN (R 3.3.0)
 withr           1.0.2   2016-06-20 CRAN (R 3.3.1)

sessionInfo():
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.12.0      RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] colorspace_1.2-6 scales_0.4.0     plyr_1.8.4       RevoUtils_10.0.1 tools_3.3.1      withr_1.0.2      gtable_0.2.0    
 [8] rstudioapi_0.6   memoise_1.0.0    Rcpp_0.12.5      ggplot2_2.1.0    grid_3.3.1       digest_0.6.9     munsell_0.4.3   

系统gcc版本号5.4.0 20160609

**Comment by qinwf** [comment]
你好，这应该是 MRO 的 bug，建议与 MRO 报告。

经过我的测试 MRO 不支持 Makevars 包含下面的内容：

```
PKG_CPPFLAGS =   -I../inst/include 
CXX_STD = CXX11
```
所有包含这个内容的包都无法安装，类似的包可以通过 GitHub 搜索找到 [link](https://github.com/search?q=CXX_STD+%3D+CXX11+PKG_CPPFLAGS&ref=reposearch&type=Code&utf8=%E2%9C%93)，比如 [sparseHessianFD](https://github.com/cran/sparseHessianFD/blob/d6190e8ce85db185fa619aff987b0605289ee758/src/Makevars.win)

```
* installing *source* package ‘sparseHessianFD’ ...
** package ‘sparseHessianFD’ successfully unpacked and MD5 sums checked
** libs
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include" -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/RcppEigen/include"      -c RcppExports.cpp -o RcppExports.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'RcppExports.o' failed
make: [RcppExports.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include" -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/RcppEigen/include"      -c color.cpp -o color.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'color.o' failed
make: [color.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I../inst/include  -DU_STATIC_IMPLEMENTATION -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/Rcpp/include" -I"/usr/lib64/microsoft-r/3.3/lib64/R/library/RcppEigen/include"      -c subst.cpp -o subst.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'subst.o' failed
make: [subst.o] Error 127 (ignored)
-shared -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -o sparseHessianFD.so RcppExports.o color.o subst.o -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -lR
sh: line 2: -shared: command not found
/usr/lib64/microsoft-r/3.3/lib64/R/share/make/shlib.mk:6: recipe for target 'sparseHessianFD.so' failed
make: *** [sparseHessianFD.so] Error 127
ERROR: compilation failed for package ‘sparseHessianFD’
* removing ‘/usr/lib64/microsoft-r/3.3/lib64/R/library/sparseHessianFD’

The downloaded source packages are in
	‘/tmp/RtmpIgnmHe/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("sparseHessianFD") :
  installation of package ‘sparseHessianFD’ had non-zero exit status
```

**Comment by alexwwang** [comment]
非常感谢！
微软果然一如既往的让人烦恼
