### ISSUE TITLE
原安装的jiebaR在Microsoft-r 3.3.1下加载运行提示grep中正则匹配模式不兼容

### ISSUE THREAD

**Issue by alexwwang** [qinwf/jiebaR#43]
错误提示是新的grep函数对unicode属性的PCRE匹配模式不兼容：

详情如下：

`> test_worker <- worker('tag')`
`> test_worker <= '这是一个测试句子。'`
`Error in grep("(*UCP)^[^⺀-　〡-﹏a-zA-Z0-9]*$", result, perl = TRUE,  : `
`  invalid regular expression '(*UCP)^[^⺀-　〡-﹏a-zA-Z0-9]*$'`
`In addition: Warning message:`
`In grep("(*UCP)^[^⺀-　〡-﹏a-zA-Z0-9]*$", result, perl = TRUE,  :`
`  PCRE pattern compilation error`
`	'this version of PCRE is not compiled with Unicode property support'`
`	at '(*UCP)^[^⺀-　〡-﹏a-zA-Z0-9]*$'`

**Comment by qinwf** [comment]
你好，这个是 MRO 的 bug，CRAN 要求所有 R 在构建的时候都需要支持 unicode pattern，MRO 为了加快构建时间，把 unicode pattern 去掉了。

参见 CRAN 注释

> PCRE must be built with UTF-8 support (not the default, and checked by @command{configure}) and support for Unicode properties is assumed by some @R{} packages. 

https://github.com/wch/r-source/blob/ceeebfaccc10fdf946920cef641d6efbd64bab59/doc/manual/R-admin.texi#L3289-L3302

MRO:

```
# Handle --enable-unicode-properties
AC_ARG_ENABLE(unicode-properties,
              AS_HELP_STRING([--enable-unicode-properties],
                             [enable Unicode properties support (implies --enable-utf)]),
, enable_unicode_properties=no)
```

https://github.com/Microsoft/microsoft-r-open/blob/6d2bbb4fc9ed0b6a5212a4694de4c14dd48d25f1/vendor/pcre-8.37/configure.ac#L182-L186

**Comment by alexwwang** [comment]
感谢菊苣的回答！
明白了。我先回退到3.3.0使用了。
