### ISSUE TITLE
jiebaR在CentOS release 6.4 (Final)环境安装失败

### ISSUE THREAD

**Issue by jackstephen** [qinwf/jiebaR#6]
错误信息如下：
install.packages("jiebaR",dep=T)
--- Please select a CRAN mirror for use in this session ---
trying URL 'http://mirrors.xmu.edu.cn/CRAN/src/contrib/jiebaR_0.4.tar.gz'
Content type 'application/x-gzip' length 63702 bytes (62 Kb)
opened URL
downloaded 62 Kb

* installing *source* package ?.iebaR?....
** package ?.iebaR?.successfully unpacked and MD5 sums checked
** libs
g++ -std=c++0x -I/usr/local/lib64/R/include -DNDEBUG -I../inst/include -DLOGGER_LEVEL=LL_WARN -I/usr/local/include -I"/usr/local/lib64/R/library/Rcpp/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algobase.h:66,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:41,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from ../inst/include/segtype.hpp:4,
                 from ../inst/include/jiebaR.h:5,
                 from RcppExports.cpp:4:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h: In constructor ?.td::pair<_T1, _T2>::pair(_U1&&, _U2&&) [with _U1 = size_t&, _U2 = long int, _T1 = long unsigned int, _T2 = const CppJieba::DictUnit*]?.
../inst/include/lib/Trie.hpp:127:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h:90: error: invalid conversion from ?.ong int?.to ?.onst CppJieba::DictUnit*?
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ?.iebaR?
* removing ?.usr/local/lib64/R/library/jiebaR?

The downloaded source packages are in
	?.tmp/RtmpGFXG2h/downloaded_packages?
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("jiebaR", dep = T) :
  installation of package ?.iebaR?.had non-zero exit status

**Comment by qinwf** [comment]
GCC 版本需要大于 4.6.3 ，因为使用了 C++11。

**Comment by jackstephen** [comment]
GCC版本升级后，搞定了。谢谢！
