### ISSUE TITLE
cidian包是不可以下载了吗

### ISSUE THREAD

**Issue by Jessica813** [qinwf/jiebaR#70]
错误: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`qinwf`) and repo name (`cidian`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by paulrhyschan** [comment]
遇到同样的问题 求解

**Comment by paulrhyschan** [comment]
https://github.com/qinwf/cidian/ 主页404了

**Comment by tianyun10** [comment]
如何解决，有哪位大神能指导一下不？

**Comment by 11232-cell** [comment]
同问.卡住了
