### ISSUE TITLE
centos 6.5下安装jiebaR失败（类型转换失败）

### ISSUE THREAD

**Issue by wa2003** [qinwf/jiebaR#9]
install.packages("jiebaR")
Installing package into ‘/home/enn_james/R/x86_64-unknown-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependency ‘jiebaRD’

试开URL’http://cran.rstudio.com/src/contrib/jiebaRD_0.1.tar.gz'
Content type 'application/x-gzip' length 5051847 bytes (4.8 MB)
==================================================
downloaded 4.8 MB

试开URL’http://cran.rstudio.com/src/contrib/jiebaR_0.5.tar.gz'
Content type 'application/x-gzip' length 63613 bytes (62 KB)
==================================================
downloaded 62 KB

* installing *source* package ‘jiebaRD’ ...
** 成功将‘jiebaRD’程序包解包并MD5和检查
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (jiebaRD)
* installing *source* package ‘jiebaR’ ...
** 成功将‘jiebaR’程序包解包并MD5和检查
** libs
g++ -std=c++0x -I/usr/local/lib64/R/include -DNDEBUG -I../inst/include -DLOGGER_LEVEL=LL_WARN -I/usr/local/include -I"/usr/local/lib64/R/library/Rcpp/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_algobase.h:66,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:41,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from ../inst/include/segtype.hpp:4,
                 from ../inst/include/jiebaR.h:5,
                 from RcppExports.cpp:4:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h: In constructor ‘std::pair<_T1, _T2>::pair(_U1&&, _U2&&) [with _U1 = size_t&, _U2 = long int, _T1 = long unsigned int, _T2 = const CppJieba::DictUnit*]’:
../inst/include/lib/Trie.hpp:127:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h:90: 错误：从类型‘long int’到类型‘const CppJieba::DictUnit*’的转换无效
make: *** [RcppExports.o] 错误 1
ERROR: compilation failed for package ‘jiebaR’
* removing ‘/home/enn_james/R/x86_64-unknown-linux-gnu-library/3.2/jiebaR’
Warning in install.packages :
  installation of package ‘jiebaR’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp9D32gT/downloaded_packages’
> install.package("jiebaR")
错误: 没有"install.package"这个函数
> install.packages("jiebaR")
Installing package into ‘/home/enn_james/R/x86_

**Comment by qinwf** [comment]
jiebaR requires GCC> 4.6.3, your version is 4.4.7.

http://qinwenfeng.com/jiebaR/basic/install.html

Please update GCC version to 4.6.3+. Maybe you can yum install it from EPEL.

Once you have GCC 4.6.3 installed, you can install jiebaR from CRAN without devtools.

It is a little bit tricky to install devtools package on centos or debian.
